pipeline {
    agent any
         tools {
                 maven 'Maven'
                 
                 //jdk 'JDK7'
             }
    stages {
        stage('Checkout from Application Repo'){
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/mahesh288646/terraform.git']]])
                
                  }
        }
        stage('Deploying-Dev') {
            steps {
                echo "Hello"
                tool name: 'Terraform', type: 'terraform'

                 }
                                }
        stage('Terraform Init') {
            steps {
                    sh "cd ${env.WORKSPACE}/AWS/Prep6/ && terraform init -input=false"
      }
    }                        
       stage('Terraform Plan') {
             steps {
                    //withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'AWSID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                                            sh "terraform remote config -backend=S3 -backend-config=bucket=labs3april42021 -backend-config=key=app/terraform-state/terraform.tfstate -backend-config=region=us-east-1"
                    //                        sh "cd ${env.WORKSPACE}/AWS/Prep6/ && terraform remote config -backend=S3 -backend-config='bucket=labs3april42021' -backend-config='key=app/terraform-state/terraform.tfstate' -backend-config='region=us-east-1' && terraform plan -input=false"
//}
       }
    }   
       stage('Terraform apply') {
            steps {
                    withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'AWSID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                      //                      sh "cd ${env.WORKSPACE}/AWS/Prep6/ && terraform remote config -backend=S3 -backend-config='bucket=labs3april42021' -backend-config='key=app/terraform-state/terraform.tfstate' -backend-config='region=us-east-1' && terraform apply --auto-approve"
}
                           }
    }   
               stage('Terraform destroy') {
            steps {
                    withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'AWSID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                                            sh "date"
                                            sh "cd ${env.WORKSPACE}/AWS/Prep6/ && terraform destroy --auto-approve"
}
                           }
    }  
    }
}