pipeline {
    agent any
         tools {
                 maven 'Maven'
                 
                 //jdk 'JDK7'
             }
    stages {
        stage('Checkout from Application Repo'){
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/mahesh288646/terraform.git']]])
                
                  }
        }
        stage('Deploying-Dev') {
            steps {
                echo "Hello"
                tool name: 'Terraform', type: 'terraform'

                 }
                                }
        stage('Terraform Init') {
            steps {
                    sh "cd ${env.WORKSPACE}/AWS/Prep6/ && terraform init -input=false"
      }
    }                        
       stage('Terraform Plan') {
             steps {
                    withCredentials([usernameColonPassword(credentialsId: 'AWSIDNEW', variable: 'AWSID')]) {
                                            sh "cd ${env.WORKSPACE}/AWS/Prep6/ && terraform plan -input=false"
}
       }
    }   
       stage('Terraform apply') {
            steps {
                    wwithCredentials([usernameColonPassword(credentialsId: 'AWSIDNEW', variable: 'AWSID')]) {
                                            sh "cd ${env.WORKSPACE}/AWS/Prep6/ && terraform apply --auto-approve"
}
                           }
    }   
               stage('Terraform destroy') {
            steps {
                    wwithCredentials([usernameColonPassword(credentialsId: 'AWSIDNEW', variable: 'AWSID')]) {
                                            sh "cd ${env.WORKSPACE}/AWS/Prep6/ && terraform destroy --auto-approve"
}
                           }
    }  
    }
}